name: CI
on: [push]
jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: actions/setup-node@v2.5.2
      - run: npm ci
      - run: npm test
